// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace apiBillFold.Models
{
    public partial class Administrador
    {
        public long Id { get; set; }
        public int IdEmpresa { get; set; }
        public int Idtipo { get; set; }
        public string? PrimerNombre { get; set; }
        public string? SegundoNombre { get; set; }
        public string? PrimerApellido { get; set; }
        public string? SegundoApellido { get; set; }
        public string? Alias { get; set; }
        public long? Dpi { get; set; }
        public byte[]? Contraseña { get; set; }
        public DateTime? FechaNacimiento { get; set; }
        public string? CodigoEmpleado { get; set; }
        public string? Nit { get; set; }
    }
}