// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace apiBillFold.Models
{
    public partial class Campana
    {
        public int Id { get; set; }
        public long? IdEmpresa { get; set; }
        public string? Nombre { get; set; }
        public string? Descripcion { get; set; }
        public DateTime? FechaCreacion { get; set; }
        public decimal? Cantidad { get; set; }
        public decimal? Monto { get; set; }
        public string? NumeroDocumento { get; set; }
        public int? IdBanco { get; set; }
        public int? Estado { get; set; }
        public int? IdAutorizador { get; set; }
        public int? IdTarjetaRegalo { get; set; }
        public int? IdBancoDestino { get; set; }
        public int? TipoCliente { get; set; }
        public string? Comprobante { get; set; }
    }
}