// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace apiBillFold.Models
{
    public partial class Categoria
    {
        public long Id { get; set; }
        public string? Nombre { get; set; }
        public long? IdEmpresa { get; set; }
        public string? Imagen { get; set; }
        public string? Descripcion { get; set; }
    }
}