// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace apiBillFold.Models
{
    public partial class Configuracion
    {
        public decimal Id { get; set; }
        public string Llave { get; set; } = null!;
        public string Valor { get; set; } = null!;
        public int? Idpais { get; set; }
        public int? Tipo { get; set; }
        public string? Escala { get; set; }
    }
}