// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace apiBillFold.Models
{
    public partial class DetalleMenu
    {
        public int Id { get; set; }
        public int? IdMenuSuperior { get; set; }
        public int? IdMenu { get; set; }
    }
}