// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace apiBillFold.Models
{
    public partial class Detallegrupo
    {
        public long Id { get; set; }
        public long? IdGrupo { get; set; }
        public long? Idempresa { get; set; }
        public DateTime? Fecha { get; set; }
        public int? Idpais { get; set; }
    }
}