// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace apiBillFold.Models
{
    public partial class Empresa
    {
        public int Id { get; set; }
        public string Nombre { get; set; } = null!;
        public string Logo { get; set; } = null!;
        public string? Frase { get; set; }
        public string? PalabraClave { get; set; }
        public string? Region { get; set; }
        public string? Moneda { get; set; }
    }
}