// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace apiBillFold.Models
{
    public partial class EmpresaSocia
    {
        public int Id { get; set; }
        public int IdEmpresa { get; set; }
        public string? Nombre { get; set; }
        public string? Direccion { get; set; }
        public string? EmailContacto { get; set; }
        public int? IdPais { get; set; }
        public int? IdMoneda { get; set; }
        public string? Nit { get; set; }
        public string? Contacto { get; set; }
        public short? TieneCredito { get; set; }
        public int? Porcentaje { get; set; }
        public short? AplicaDisponible { get; set; }
        public string? Logo { get; set; }
        public short? Estado { get; set; }
        public int? Idpais1 { get; set; }
        public short? AplicaRecargo { get; set; }
        public decimal? PorcentajeXf { get; set; }
        public decimal? PorcentajeRecargo { get; set; }
        public int? TipoEmpresa { get; set; }
        public string? UidTienda { get; set; }
        public short? AplicaNegociacion { get; set; }
        public decimal? PorcentajeNegociacion { get; set; }
        public short? AplicaEnvio { get; set; }
        public decimal? PorcentajeEnvio { get; set; }
        public short? TiendaLinea { get; set; }
        public short? TiendaFisica { get; set; }
    }
}