// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace apiBillFold.Models
{
    public partial class EmpresaFinanciamiento
    {
        public int Id { get; set; }
        public int IdEmpresa { get; set; }
        public string? Autorizador { get; set; }
        public string? UrlServicio { get; set; }
        public decimal? Porcentaje { get; set; }
        public int? Meses { get; set; }
        public int? IdMoneda { get; set; }
        public short? TieneCredito { get; set; }
        public decimal? CostoOperacion { get; set; }
    }
}