// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace apiBillFold.Models
{
    public partial class getAsociacionDetallePaisResult
    {
        public long id { get; set; }
        public long? idGrupo { get; set; }
        public long? idempresa { get; set; }
        public DateTime? fecha { get; set; }
        public int? idpais { get; set; }
    }
}
