// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace apiBillFold.Models
{
    public partial class Grupo
    {
        public long Id { get; set; }
        public string? Nombre { get; set; }
        public DateTime? FechaCreacion { get; set; }
        public string? Descripcion { get; set; }
        public short? Estado { get; set; }
        public int? Idpais { get; set; }
    }
}