// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace apiBillFold.Models
{
    public partial class Institucionesfinancieras
    {
        public int Id { get; set; }
        public string? Nombre { get; set; }
        public string? Codigo { get; set; }
        public int? Tipo { get; set; }
        public int? Pais { get; set; }
        public int? Peso { get; set; }
        public int? Recibe { get; set; }
        public int? Envia { get; set; }
    }
}