// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace apiBillFold.Models
{
    public partial class InvitacionesPendientes
    {
        public long Id { get; set; }
        public long IdEmpresa { get; set; }
        public string? Correo { get; set; }
        public string? Telefono { get; set; }
        public short? Enviado { get; set; }
        public decimal? Monto { get; set; }
        public short? Canjeado { get; set; }
        public DateTime? FechaEnvio { get; set; }
        public DateTime? FechaCanje { get; set; }
        public string? Nombre { get; set; }
    }
}