// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace apiBillFold.Models
{
    public partial class ManejoIngresoEmpleadoResult
    {
        public long Id { get; set; }
        public string? PrimerNombre { get; set; }
        public string? SegundoNombre { get; set; }
        public string? otrosNombres { get; set; }
        public string? PrimerApellido { get; set; }
        public string? SegundoApellido { get; set; }
        public string? ApellidoCasada { get; set; }
        public DateTime? fechaNacimiento { get; set; }
        public string Codigoempleado { get; set; } = default!;
        public string Nit { get; set; } = default!;
        [Column("Salario", TypeName = "decimal(18,0)")]
        public decimal Salario { get; set; }
        [Column("disponible", TypeName = "decimal(18,2)")]
        public decimal disponible { get; set; }
        public string DPI { get; set; } = default!;
        public string alias { get; set; } = default!;
        public int Estado { get; set; }
        public long idEmpresa { get; set; }
        public byte[]? contrasena { get; set; }
    }
}
