// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace apiBillFold.Models
{
    public partial class ManejoIngresoResult
    {
        public long id { get; set; }
        public int idEmpresa { get; set; }
        public int idtipo { get; set; }
        public string? primerNombre { get; set; }
        public string? segundoNombre { get; set; }
        public string? primerApellido { get; set; }
        public string? segundoApellido { get; set; }
        public string? alias { get; set; }
        public long? dpi { get; set; }
        public byte[]? contraseña { get; set; }
        public DateTime? fechaNacimiento { get; set; }
        public string? codigoEmpleado { get; set; }
        public string? nit { get; set; }
    }
}
