// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace apiBillFold.Models
{
    public partial class Menu
    {
        public long Id { get; set; }
        public int Idfuncion { get; set; }
        public string? Ruta { get; set; }
        public int? Peso { get; set; }
    }
}