// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace apiBillFold.Models
{
    public partial class Pais
    {
        public int Id { get; set; }
        public string? Nombre { get; set; }
        public short? Activo { get; set; }
        public string? Logo { get; set; }
        public string? SimboloMoneda { get; set; }
        public string? Moneda { get; set; }
        public string? Simbolo { get; set; }
    }
}