// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace apiBillFold.Models
{
    public partial class Promocion
    {
        public int Id { get; set; }
        public string? Nombre { get; set; }
        public string? Descripcion { get; set; }
        public int? Tipo { get; set; }
        public DateTime? FechaInicio { get; set; }
        public DateTime? Fechafin { get; set; }
        public decimal? MontoMinimo { get; set; }
        public decimal? MontoMaximo { get; set; }
        public decimal? MontoAplicar { get; set; }
        public decimal? Montodividir { get; set; }
        public decimal? PorcentajeAplicar { get; set; }
        public short EsGeneral { get; set; }
    }
}