// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace apiBillFold.Models
{
    public partial class Saldodisponible
    {
        public long Id { get; set; }
        public long Idusuario { get; set; }
        public decimal? SaldoDisponible1 { get; set; }
        public decimal? SaldoMaximo { get; set; }
        public DateTime? FechaCreacion { get; set; }
        public DateTime? FechaModificacion { get; set; }
        public int? IdMoneda { get; set; }
        public int? IdTipo { get; set; }
    }
}