// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace apiBillFold.Models
{
    public partial class Tienda
    {
        public long Id { get; set; }
        public string? Nombre { get; set; }
        public string? Direccion { get; set; }
        public string? RazonSocial { get; set; }
        public string? Nit { get; set; }
        public string? Longitud { get; set; }
        public string? Latitud { get; set; }
        public long? IdEmpresaSocia { get; set; }
    }
}