// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace apiBillFold.Models
{
    public partial class TipoTransaccion
    {
        public int Id { get; set; }
        public string Llave { get; set; } = null!;
        public int Direccion { get; set; }
    }
}