// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace apiBillFold.Models
{
    public partial class Token
    {
        public long Id { get; set; }
        public long? Idusuario { get; set; }
        public string? Token1 { get; set; }
        public DateTime? Fechacreacion { get; set; }
        public short? Estado { get; set; }
        public string? Tipo { get; set; }
        public string? Valor { get; set; }
        public long? Comercio { get; set; }
        public decimal? Monto { get; set; }
    }
}