// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace apiBillFold.Models
{
    public partial class TransaccionesCampana
    {
        public long Id { get; set; }
        public string? Correo { get; set; }
        public decimal? Monto { get; set; }
        public int? Estado { get; set; }
        public int? IdCampana { get; set; }
    }
}