// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace apiBillFold.Models
{
    public partial class UsuarioTelefono
    {
        public long Id { get; set; }
        public long IdEmpleado { get; set; }
        public string? Numero { get; set; }
        public short? Tipo { get; set; }
        public string? Alias { get; set; }
    }
}