// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace apiBillFold.Models
{
    public partial class UsuarioExterno
    {
        public long Id { get; set; }
        public string? Nombres { get; set; }
        public string? Apellidos { get; set; }
        public int? Telefono { get; set; }
        public string? Correo { get; set; }
        public long? IdUsuario { get; set; }
        public string? Foto { get; set; }
        public short? Politica { get; set; }
        public string? Hash { get; set; }
    }
}