// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace apiBillFold.Models
{
    public partial class UsuarioTarjeta
    {
        public long Id { get; set; }
        public long? IdUsuario { get; set; }
        public string? Tarjeta { get; set; }
        public string? Nombre { get; set; }
        public string? Apellido { get; set; }
        public string? TipoTarjeta { get; set; }
        public string? FechaExpiracion { get; set; }
        public string? Cvv { get; set; }
        public long? DireccionId { get; set; }
    }
}