// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace apiBillFold.Models
{
    public partial class UsuarioDireccion
    {
        public long Id { get; set; }
        public long IdUsuario { get; set; }
        public string? DireccionFiscal { get; set; }
        public string? Ubicacion { get; set; }
        public int Departamento { get; set; }
        public int Municipio { get; set; }
        public string? Colonia { get; set; }
        public string? Zona { get; set; }
        public string? Hub { get; set; }
        public string? Detalle { get; set; }
        public string? Latitud { get; set; }
        public string? Longitud { get; set; }
        public int? Zip { get; set; }
        public int? Pais { get; set; }
        public string? NumeroCasa { get; set; }
        public string? Indicaciones { get; set; }
        public string? Alias { get; set; }
    }
}