// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace apiBillFold.Models
{
    public partial class UsuarioCuenta
    {
        public long Id { get; set; }
        public long IdUsuario { get; set; }
        public string? Descripcion { get; set; }
        public DateTime? Fecha { get; set; }
        public string? Usuario { get; set; }
        public decimal? Saldo { get; set; }
        public string? Llave { get; set; }
    }
}