// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace apiBillFold.Models
{
    public partial class UsuarioMovimiento
    {
        public long Id { get; set; }
        public long IdUsuario { get; set; }
        public long Idcuenta { get; set; }
        public decimal? Monto { get; set; }
        public int? Tipo { get; set; }
        public string? Documento { get; set; }
        public string? Descripcion { get; set; }
        public DateTime? Fecha { get; set; }
        public string? Usuario { get; set; }
        public long? MovContable { get; set; }
        public string? Ubicacion { get; set; }
        public string? Sfecha { get; set; }
    }
}