// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace apiBillFold.Models
{
    public partial class validarTokenResult
    {
        public decimal? id { get; set; }
    }
}
